services:
  database:
    image: mysql:latest
    restart: on-failure[:5]
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20      
    ports:
      - '3506:3306'
    volumes:
      - db:/var/lib/mysql
      - ./src/sql/:/docker-entrypoint-initdb.d
  socketfit:
    image: socketfit
    restart: on-failure[:5]
    depends_on:
      database:
        condition: service_healthy
    ports:
      - '5732:8080'
    expose:
      - '5732'

volumes:
  db: